# Generated by Django 5.2.6 on 2025-09-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view book data'), ('can_create', 'Can create new books'), ('can_edit', 'Can edit existing books'), ('can_delete', 'Can delete books')]},
        ),
    ]
